
project 'BarrageCloudSDKDemo.xcodeproj'

use_frameworks!

platform :ios, '13.0'

target 'BarrageCloudSDKDemo' do
pod 'AgoraRtcEngine_iOS', '4.2.2'
pod 'Kingfisher', '7.9.1'

pod 'SwiftProtobuf', '1.24.0'

pod 'RTMTokenBuilder'

pod 'SVProgressHUD'

pod 'IQKeyboardManager'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end

